/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    AppBreadcrumbs: typeof import('./components/AppBreadcrumbs.vue')['default']
    AppEmpty: typeof import('./components/AppEmpty.vue')['default']
    AppFormStyles: typeof import('./components/AppFormStyles.vue')['default']
    AppLoading: typeof import('./components/AppLoading.vue')['default']
    AppTable: typeof import('./components/AppTable.vue')['default']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LineChart: typeof import('./components/LineChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AAvatar: typeof import('ant-design-vue/es')['Avatar']
  const ABadge: typeof import('ant-design-vue/es')['Badge']
  const AButton: typeof import('ant-design-vue/es')['Button']
  const ACard: typeof import('ant-design-vue/es')['Card']
  const AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
  const ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
  const ADivider: typeof import('ant-design-vue/es')['Divider']
  const ADropdown: typeof import('ant-design-vue/es')['Dropdown']
  const AForm: typeof import('ant-design-vue/es')['Form']
  const AFormItem: typeof import('ant-design-vue/es')['FormItem']
  const AInput: typeof import('ant-design-vue/es')['Input']
  const AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
  const AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
  const AMenu: typeof import('ant-design-vue/es')['Menu']
  const AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
  const AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
  const APagination: typeof import('ant-design-vue/es')['Pagination']
  const APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
  const AppBreadcrumbs: typeof import('./components/AppBreadcrumbs.vue')['default']
  const AppEmpty: typeof import('./components/AppEmpty.vue')['default']
  const AppFormStyles: typeof import('./components/AppFormStyles.vue')['default']
  const AppLoading: typeof import('./components/AppLoading.vue')['default']
  const AppTable: typeof import('./components/AppTable.vue')['default']
  const ASelect: typeof import('ant-design-vue/es')['Select']
  const ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
  const ASpin: typeof import('ant-design-vue/es')['Spin']
  const ATable: typeof import('ant-design-vue/es')['Table']
  const ATag: typeof import('ant-design-vue/es')['Tag']
  const ATextarea: typeof import('ant-design-vue/es')['Textarea']
  const HelloWorld: typeof import('./components/HelloWorld.vue')['default']
  const LineChart: typeof import('./components/LineChart.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}